name: blog_builder
description: A static site generator for markdown blogs
version: 1.0.0
publish_to: none # Prevent accidental publishing

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  args: ^2.4.2 # Updated version
  path: ^1.9.0 # Updated version
  yaml: ^3.1.2
  markdown: ^7.1.1 # Added for markdown parsing
  xml: ^6.3.0    # Added for sitemap generator (though not used in build yet)
  liquify: ^1.0.1

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0

executables:
  blog_builder: blog_builder
